# -*- mode: python ; coding: utf-8 -*-
import os

# Get absolute path to src directory
src_path = os.path.abspath('src')

a = Analysis(
    ['src\\main.py'],
    pathex=[src_path],
    binaries=[],
    datas=[],
    hiddenimports=[
        'ui',
        'ui.application_controller',
        'ui.display_tab',
        'ui.solver_tab',
        'ui.builders',
        'ui.builders.display_ui',
        'ui.builders.solver_ui',
        'ui.dialogs',
        'ui.dialogs.material_profile_dialog',
        'ui.handlers',
        'ui.handlers.analysis_handler',
        'ui.handlers.display_animation_handler',
        'ui.handlers.display_base_handler',
        'ui.handlers.display_export_handler',
        'ui.handlers.display_file_handler',
        'ui.handlers.display_interaction_handler',
        'ui.handlers.display_results_handler',
        'ui.handlers.display_state',
        'ui.handlers.display_visualization_handler',
        'ui.handlers.file_handler',
        'ui.handlers.log_handler',
        'ui.handlers.navigator_handler',
        'ui.handlers.plotting_handler',
        'ui.handlers.settings_handler',
        'ui.handlers.ui_state_handler',
        'ui.styles',
        'ui.styles.style_constants',
        'ui.widgets',
        'ui.widgets.console',
        'ui.widgets.dialogs',
        'ui.widgets.editable_table',
        'ui.widgets.plotting',
        'core',
        'core.computation',
        'core.data_models',
        'core.plasticity',
        'core.visualization',
        'solver',
        'solver.engine',
        'solver.plasticity_engine',
        'file_io',
        'file_io.exporters',
        'file_io.fea_utilities',
        'file_io.loaders',
        'file_io.validators',
        'utils',
        'utils.constants',
        'utils.file_utils',
        'utils.node_utils',
        'utils.torch_setup',
    ],
    hookspath=['hooks'],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='MARS',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='MARS',
)
